### Get all products
GET http://localhost:3000/products

### Get one product
GET http://localhost:3000/products/68324446f9111e7b9d38148e

### Create product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "JBL headphones with microphone",
    "description": "Headphones with built-in stereo microphone, ideal for video calls and gaming.",
    "price": 39.9,
    "category": "Accessories",
    "stock": 40,
    "sku": "JBLMIC2024"
}

### Update product
PUT http://localhost:3000/products/68324488f9111e7b9d381491
Content-Type: application/json

{
    "name": "Laptop Lenovo",
    "description": "Work laptop with 16GB RAM",
    "stock": 15,
    "sku": "LENOVO2023"
  }

### Delete product
DELETE http://localhost:3000/products/68324446f9111e7b9d38148e


############################# SEGUNDA COLECCION ##################################
### Get all brands
GET http://localhost:3000/brands

### Create a new brand
POST http://localhost:3000/brands
Content-Type: application/json

{
  "name": "HP",
  "country": "United States",
  "founded": 1939,
  "description": "American company known for printers, computers, and IT services.",
  "website": "https://www.hp.com",
  "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/3/3a/HP_logo_2012.svg",
  "active": true
}

### Update a brand
PUT http://localhost:3000/brands/683523ea1736a9b10db1fd96
Content-Type: application/json

{
  "name": "HP",
  "country": "United States",
  "founded": 1939,
  "description": "American company known for printers, computers, and IT services.",
  "website": "https://www.hp.com",
  "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/3/3a/HP_logo_2012.svg",
  "active": true
}

### Delete a brand
DELETE http://localhost:3000/brands/